require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stock_movements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StockMovement. As you add validations to StockMovement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StockMovement.create! valid_attributes
      get stock_movements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stock_movement = StockMovement.create! valid_attributes
      get stock_movement_url(stock_movement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stock_movement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stock_movement = StockMovement.create! valid_attributes
      get edit_stock_movement_url(stock_movement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StockMovement" do
        expect {
          post stock_movements_url, params: { stock_movement: valid_attributes }
        }.to change(StockMovement, :count).by(1)
      end

      it "redirects to the created stock_movement" do
        post stock_movements_url, params: { stock_movement: valid_attributes }
        expect(response).to redirect_to(stock_movement_url(StockMovement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StockMovement" do
        expect {
          post stock_movements_url, params: { stock_movement: invalid_attributes }
        }.to change(StockMovement, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post stock_movements_url, params: { stock_movement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stock_movement" do
        stock_movement = StockMovement.create! valid_attributes
        patch stock_movement_url(stock_movement), params: { stock_movement: new_attributes }
        stock_movement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stock_movement" do
        stock_movement = StockMovement.create! valid_attributes
        patch stock_movement_url(stock_movement), params: { stock_movement: new_attributes }
        stock_movement.reload
        expect(response).to redirect_to(stock_movement_url(stock_movement))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        stock_movement = StockMovement.create! valid_attributes
        patch stock_movement_url(stock_movement), params: { stock_movement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stock_movement" do
      stock_movement = StockMovement.create! valid_attributes
      expect {
        delete stock_movement_url(stock_movement)
      }.to change(StockMovement, :count).by(-1)
    end

    it "redirects to the stock_movements list" do
      stock_movement = StockMovement.create! valid_attributes
      delete stock_movement_url(stock_movement)
      expect(response).to redirect_to(stock_movements_url)
    end
  end
end
